# Generated by Django 4.1.3 on 2022-11-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_window_archive_alter_window_favourites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="window",
            old_name="favourites",
            new_name="favourite",
        ),
    ]
