# Generated by Django 4.1.3 on 2022-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_rename_favourites_window_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
