# Generated by Django 4.1.3 on 2022-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_entry_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="docfile",
            field=models.FileField(blank=True, upload_to="documents/%Y/%m/%d"),
        ),
    ]
